### PR TITLE
fix: Korean input trigger keydown event twice

### PR DESCRIPTION
**Pull request by shrilakshmishastry**
>[!NOTE]
> The solution needs to be tested by a proper Korean language user. Being a non-Korean lang user, I can change the keyboard and type input and test, but I will not be able to say whether what I tested is proper according to the Korean language, 

## Issue

Korean and Japanese languages characters are formed using the compositions of keys. 

From GPT:

Composition-based Input:
Korean, like many East Asian languages, often uses an Input Method Editor (IME) for text entry. This involves a composition process where multiple keystrokes may be required to form a single character.

Challenges:

1. The value of the input field may not be final until the composition is complete.
2. Key events may fire multiple times for a single Korean character.
3. The keyCode or which properties may not accurately represent the Korean character being input.

The issue we were facing is that the keys were still composing when we were handling `onKeyDown ` event. By the time the composition is done, it is used to trigger one more time enter and last character. 

can read more [here](https://github.com/vuejs/vue/issues/10277)

## Fix

Add a composing check-in on the KeyDown event to handle the next stages. Though Key events might fire multiple times, this makes sure, that until all composing is done enter is not triggered .
 
 
 Why the handling is added in `onKeyDown` event not on `onChange`?
 - we are concentrating on `enter key` which is the terminating key. It's not considered as value in the input tag. 

This fixes https://github.com/react-tags/react-tags/issues/988

## SCREEN RECORDINGS

English lang
https://github.com/user-attachments/assets/fe4060cf-d51f-4fa5-9efd-7f99a20f575f

Korean lang
https://github.com/user-attachments/assets/80ba9760-6184-4faa-8a76-4189ebc8901b

### CODE REVIEW

**Comment by shrilakshmishastry** [comment]
Hey @ad1992 , here is the fix for https://github.com/react-tags/react-tags/issues/988. How to ask the bug reporter to try this out and check whether this works ?

**Comment by ad1992** [comment]
@shrilakshmishastry looks like this has fuzzy PR changes as well, can you only push the changes related to the fix?

**Comment by ad1992** [comment]
@shrilakshmishastry please leave a comment about why this PR is closed

**Comment by shrilakshmishastry** [comment]
The PR is closed as the branch is cut out from non master branch

**Pull request closed without merging**
